# Generated by Django 4.0.4 on 2022-05-13 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_department_director_alter_department_staff_and_more'),
        ('staff', '0002_alter_doctor_person_alter_doctor_user_type_and_more'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_patient',
            name='date_of_adm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='in_patient',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.diagnose'),
        ),
        migrations.AlterField(
            model_name='in_patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor'),
        ),
        migrations.AlterField(
            model_name='in_patient',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.room'),
        ),
        migrations.AlterField(
            model_name='out_patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='out_patient',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.diagnose'),
        ),
        migrations.AlterField(
            model_name='out_patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor'),
        ),
    ]
