# Generated by Django 4.0.4 on 2022-05-13 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_doctor_person_alter_doctor_user_type_and_more'),
        ('reception', '0002_alter_in_patient_date_of_adm_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.patient'),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.test'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.diagnose'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='absorved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='inactivated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='live',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='oral',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccineapplied',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccineapplied',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nurse'),
        ),
        migrations.AlterField(
            model_name='vaccineapplied',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.patient'),
        ),
        migrations.AlterField(
            model_name='vaccineapplied',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.vaccine'),
        ),
    ]
