# Generated by Django 4.0.4 on 2022-05-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_doctor_person_alter_doctor_user_type_and_more'),
        ('reception', '0002_alter_in_patient_date_of_adm_and_more'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='staff.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(blank=True, default='Kagando Mission Hospital', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='reception.patient'),
        ),
    ]
